server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/springdatajpa
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver




  #To get output of query on console
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

    hibernate:
      ddl-auto: update
      show-sql : true
  jackson:
    time-zone: IST

